In [2]:
import numpy as np

In [3]:
list1 = [20, 27, 9, 12, 31, 17, 4, 50, 39, 35]
arr = np.array(list1)

arr_4 = arr * 4
print(arr_4)

arr_mean = np.mean(arr)
print(arr_mean)

arr_median = np.median(arr)
print(arr_median)

arr_standard_deviation = np.std(arr)
print(arr_standard_deviation)

arr_argmax = np.argmax(arr)
print(arr_argmax)

arr_argmin = np.argmin(arr)
print(arr_argmin)

print(arr[arr_argmax])
print(arr[arr_argmin])

arr_greater_than_20 = arr[arr > 20]
print(arr_greater_than_20)

[ 80 108  36  48 124  68  16 200 156 140]
24.4
23.5
13.828955130450023
7
6
50
4
[27 31 50 39 35]


In [4]:
matrix = [
[5, 12, 17, 9],
[8, 21, 14, 3],
[6, 13, 19, 11]
]

arr = np.array(matrix)

print(arr.shape)

print(arr[:, 2])

print(arr[1, :])

print(arr*2)

print(np.mean(arr, axis = 0))

print(np.mean(arr))

print(np.max(arr, axis = 1))
print(np.min(arr, axis = 0))

arr2 = arr.flatten()
print(arr2)
    # converts from a 2D array into a 1D array

arr2_min = np.argmin(arr2)
print(arr2_min)
arr2_max = np.argmax(arr2)
print(arr2_max)

# np.unravel_index(arr2, arr.shape)

arr_greater_than_15 = arr[arr > 15]
print(arr_greater_than_15)

sorted_arr = np.sort(arr, axis=1)
print(sorted_arr)


(3, 4)
[17 14 19]
[ 8 21 14  3]
[[10 24 34 18]
 [16 42 28  6]
 [12 26 38 22]]
[ 6.33333333 15.33333333 16.66666667  7.66666667]
11.5
[17 21 19]
[ 5 12 14  3]
[ 5 12 17  9  8 21 14  3  6 13 19 11]
7
5
[17 21 19]
[[ 5  9 12 17]
 [ 3  8 14 21]
 [ 6 11 13 19]]


In [7]:
# 4: Prime Star Systems

import math

arr = np.array([
[2, 3, 5],
[14, 6, 8],
[11, 13, 17],
[7, 10, 13]
])

# Use trail division to determine if prime
def is_prime(n):
    # Handle special cases
    if n <= 1:
        return False
    if n <= 3:
        return True
    
    # Handle even numbers
    if n % 2 == 0:
        return False
        
    # Check for factors from 3 up to sqrt(n)
    # The step is 2 to only check odd numbers
    i = 3
    while i <= math.sqrt(n):
        if n % i == 0:
            return False
        i += 2
        return True

def find_primes(arr):
    prime_rows = []
    for row in arr:
           if any(is_prime(num) for num in row):
            prime_rows.append(row)
    return np.array(prime_rows)
print(find_primes(arr))


[[ 2  3  5]
 [11 13 17]
 [ 7 10 13]]


In [69]:
# 5: Checkers

def checkerboard():
    board = np.zeros((7, 7), dtype = int)
    # even rows:
    board[::2, ::2] = 1
    # odd rows:
    board[1::2, 1::2] = 1
    return board
print(checkerboard())

[[1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]]


In [11]:
# 6: Expanding Universe

universe = np.array(['galaxy', 'clusters'])

def expansion(arr, n):
    expanded_list = []
    spacer = ' ' * n
    for character in universe:
        character_list = list(character)
        expanded_list.append(spacer.join(list(character)))
    return np.array(expanded_list)

print(expansion(universe, 2))

['g  a  l  a  x  y' 'c  l  u  s  t  e  r  s']


In [19]:
# 7: Second-Brightest Star

arr = np.array([[1123, 1456, 1789, 1324, 1876],
                [1567, 1987, 1678, 1405, 1589],
                [1345, 1654, 1523, 1109, 1923],
                [1298, 1890, 1367, 1784, 1432],
                [1823, 1756, 1489, 1672, 1550]])

def second_brightest(arr):
    sorted_stars = np.sort(arr, axis=1)
    return sorted_stars[:, -2]

print(second_brightest(arr))
        

[1789 1678 1654 1784 1756]
